// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WallabagReducer.Net;

namespace WallabagReducer.Net.Migrations
{
    [DbContext(typeof(WallabagContext))]
    [Migration("20190127153737_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("WallabagReducer.Net.HNArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContentUrl");

                    b.Property<int>("ContentWBId");

                    b.Property<string>("SourceUrl");

                    b.Property<int>("SourceWBId");

                    b.HasKey("Id");

                    b.ToTable("ProcessedHNArticles");
                });
#pragma warning restore 612, 618
        }
    }
}
